PreCommit:
 RuboCop:
   enabled: true
   on_warn: fail

 TrailingWhitespace:
   enabled: true
   exclude:
     - '**/db/structure.sql' # Ignore trailing whitespace in generated files
     - 'README.md'

PrePush:
  RSpec:
    enabled: true
    on_warn: fail