AllCops:
  Exclude:
    - db/**
    - db/migrate/**
    - bin/**

Metrics/LineLength:
  Max: 120
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/simple_form.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - config/**/*
    - spec/**/*

Documentation:
  Enabled: false